footer-html
vitulya/team-project pull request #5
Opened 2022-10-12 19:03 UTC by Julia1232

2022-10-12 20:09 UTC, vitulya requested changes

2022-10-12 20:09 UTC, vitulya commented on src/partials/footer.html
> +    <nav class="menu">
додати дів с класом container(обгорнути ним весь контент)

2022-10-12 20:09 UTC, vitulya commented on src/partials/footer.html
> +        <ul class="footer-links__item">
тут краще клас ooter-wrapper__list і плюс нада ще додати просто клас list щоб скидало стилі(тобто маркери)

2022-10-12 20:09 UTC, vitulya commented on src/partials/footer.html
> +            <li class="footer-links__deskription">Terms of Service</li>
а в усіх лішках вже зробити клас ooter-wrapper__item
і в кожній лішці ще має бути посилання вкладене, а в ньому вже цей опис, а в посилання вже клас footer-wrapper__link

2022-10-12 20:09 UTC, vitulya commented on src/partials/footer.html
> +                    <input type="mail" class="contact-form">
не пам*ятаю чи це обов*язково, але в домашках нам казали задавати ще нейм інпутам, типу так для прикладу з нашого модального вікна
<input class="modal-input" type="text" name="user-name" />

2022-10-12 20:09 UTC, vitulya commented on src/partials/footer.html
> +            <button type="submit" class="contact-form-btn">Subscribe</button>
сюди також добавити базовий клас button

2022-10-12 20:09 UTC, vitulya commented on src/partials/footer.html
> +    <nav class="menu">
В Footer-і знаходяться два блока.
В першому блоці знаходиться логотип, блок навігації, а також блок для підписки.--це з завдань

тобто тобі потрібно зробити два діва у футері, в один вкластилоготип, навігаці, форму. В інший -все остальне

2022-10-12 20:09 UTC, vitulya commented on src/partials/footer.html
> +    <div class="footer-links">
тут краще змінити клас, бо такий нам буде потрібний трішки нижче, тут краще написати типу footer-wrapper

2022-10-13 10:50 UTC, vitulya requested changes

2022-10-13 10:50 UTC, vitulya commented on src/partials/footer.html
> +                <p class="sub__policy">By subscribing you agree to with our <a href="" class="sub__policy-link">Privacy Policy</a>
винеси це з форми  і в href ссилки положи посилання на сторінку цієї конфеденційності
Також в блоці підписки потрібно додати опис з посиланням на Privacy Policy (політику конфіденційності).

2022-10-13 11:16 UTC, vitulya requested changes

2022-10-13 11:16 UTC, vitulya commented on src/partials/footer.html
> +        <div class="footer__navigation">
тут в діва напевно краще інший клас, це ні на що не впливає, але у навігейшн форма не має входити, назвати якось загально, так як там знаходить і навігація і підписка і лого, напр футер-контент, але це таке,ящо ти проти може бути і так

В першому блоці знаходиться логотип, блок навігації, а також блок для підписки.

2022-10-13 11:16 UTC, vitulya commented on src/partials/footer.html
> +                <li class="footer-wrapper__item"><a href="" class="footer-wrapper__link">Privacy Policy</a></li>
тут теж напевно повставляй ссилкі якісь у кожну лішку

2022-10-13 11:24 UTC, Julia1232 commented on src/partials/footer.html
> +        <div class="footer__navigation">
Назвала footer-container

2022-10-13 11:25 UTC, Julia1232 commented on src/partials/footer.html
> +                <li class="footer-wrapper__item"><a href="" class="footer-wrapper__link">Privacy Policy</a></li>
первую- поставила, остальные две там настройки и что-то еще, я думаю, их не нужно

2022-10-13 11:56 UTC, vitulya approved these changes

2022-10-13 11:56 UTC, merged