team-project
vitulya/team-project pull request #6
Opened 2022-10-12 20:17 UTC by abeduhin

HTML секции favorites

2022-10-12 20:37 UTC, vitulya requested changes

2022-10-12 20:37 UTC, vitulya commented on src/partials/favorites.html
> +<div class="container">
тобі потрібно добавити перед перед контейнером тег секція з класом наприклад  favorites, і весь контент що в тебе є вкласти в цю секцію(тобто контейнер весь твій)
      <section class="">
           
      </section>

2022-10-12 20:37 UTC, vitulya commented on src/partials/favorites.html
> +    <div class="favorites_text">
в класах ми домовились ставити два пробіли favorites__text

2022-10-12 20:37 UTC, vitulya commented on src/partials/favorites.html
> +        <h2 class="favorites_hedline">Some of Our Favorites</h2>
для  заголовку секцій будемо задавати один клас загальний, а якщо потім буде потрібно, задаватимемо додатковий,  тому що для заголовків секцій будемо писати стилі у компоненті, тому щ овони всі однакові, щоб не писати одне і теж сто раз, ьому садай клас section-title

2022-10-12 20:37 UTC, vitulya commented on src/partials/favorites.html
> +    <ul class="favorites_dish">
сюди потрібно дописати ще клас,який ми писали для скидання стилів, тобто  list, щоб не було маркерів

2022-10-13 12:01 UTC, abeduhin commented on src/partials/favorites.html
> +<div class="container">
зробив

2022-10-13 14:14 UTC, vitulya requested changes

2022-10-13 14:14 UTC, vitulya commented on src/partials/favorites.html
> +                <img src="./images/favoritas_img/gamburger_mobile1.jpg"
забери ширину картинки, так як вона буде не стабільна а різна на мобілці, планшеті і декстопі.
ми потім в scss будемо її вираховувати флекс безісом

2022-10-13 14:14 UTC, vitulya commented on src/partials/favorites.html
> +                 media="(min-width: 480px)"
тут пропиши max-wigth: 767px

2022-10-13 14:14 UTC, vitulya commented on src/partials/favorites.html
> +                <img src="./images/favoritas_img/pasta_mobil2.jpg"
те саме забери ширину

2022-10-13 14:14 UTC, vitulya commented on src/partials/favorites.html
> +                 media="(min-width: 480px)"
тут пропиши max-wigth: 767px
і так в кожному пункті

2022-10-13 15:16 UTC, vitulya requested changes

2022-10-13 15:16 UTC, vitulya commented on src/partials/favorites.html
> +                 media="(mav-width: 767px)"
помилка в слові max   і так у всіх де змінював

2022-10-13 15:33 UTC, abeduhin commented on src/partials/favorites.html
> +                 media="(mav-width: 767px)"
Исправил. смотри крайний, я там ещё класс добавил для отсутствующих в мобильной версии

2022-10-13 15:41 UTC, vitulya requested changes

2022-10-13 15:41 UTC, vitulya commented on src/partials/favorites.html
> +    <ul class="favorites__dish list">
тут мені здається краще б клас favorites-dish

2022-10-13 15:41 UTC, vitulya commented on src/partials/favorites.html
> +        <li class="favorites__dish__img">
а тут вже favorites-dish__img
так за бемом правильніше буде

2022-10-13 17:33 UTC, abeduhin commented on src/partials/favorites.html
> +        <li class="favorites__dish__img">
не вопрос сейчас вышлю

2022-10-13 18:00 UTC, vitulya approved these changes

2022-10-13 18:00 UTC, merged